// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package calc is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	CalcRequest
	CalcReply
*/
package calc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CalcRequest struct {
	IResult int32  `protobuf:"varint,1,opt,name=iResult" json:"iResult,omitempty"`
	SResult string `protobuf:"bytes,2,opt,name=sResult" json:"sResult,omitempty"`
}

func (m *CalcRequest) Reset()                    { *m = CalcRequest{} }
func (m *CalcRequest) String() string            { return proto.CompactTextString(m) }
func (*CalcRequest) ProtoMessage()               {}
func (*CalcRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CalcRequest) GetIResult() int32 {
	if m != nil {
		return m.IResult
	}
	return 0
}

func (m *CalcRequest) GetSResult() string {
	if m != nil {
		return m.SResult
	}
	return ""
}

type CalcReply struct {
	IResult int32  `protobuf:"varint,1,opt,name=iResult" json:"iResult,omitempty"`
	SResult string `protobuf:"bytes,2,opt,name=sResult" json:"sResult,omitempty"`
}

func (m *CalcReply) Reset()                    { *m = CalcReply{} }
func (m *CalcReply) String() string            { return proto.CompactTextString(m) }
func (*CalcReply) ProtoMessage()               {}
func (*CalcReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CalcReply) GetIResult() int32 {
	if m != nil {
		return m.IResult
	}
	return 0
}

func (m *CalcReply) GetSResult() string {
	if m != nil {
		return m.SResult
	}
	return ""
}

func init() {
	proto.RegisterType((*CalcRequest)(nil), "calc.CalcRequest")
	proto.RegisterType((*CalcReply)(nil), "calc.CalcReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Calc service

type CalcClient interface {
	CalcResult(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcReply, error)
}

type calcClient struct {
	cc *grpc.ClientConn
}

func NewCalcClient(cc *grpc.ClientConn) CalcClient {
	return &calcClient{cc}
}

func (c *calcClient) CalcResult(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcReply, error) {
	out := new(CalcReply)
	err := grpc.Invoke(ctx, "/calc.Calc/CalcResult", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Calc service

type CalcServer interface {
	CalcResult(context.Context, *CalcRequest) (*CalcReply, error)
}

func RegisterCalcServer(s *grpc.Server, srv CalcServer) {
	s.RegisterService(&_Calc_serviceDesc, srv)
}

func _Calc_CalcResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).CalcResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.Calc/CalcResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).CalcResult(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.Calc",
	HandlerType: (*CalcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalcResult",
			Handler:    _Calc_CalcResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x4e, 0xcc, 0x49, 0x56,
	0x72, 0xe4, 0xe2, 0x76, 0x4e, 0xcc, 0x49, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92,
	0xe0, 0x62, 0xcf, 0x0c, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d,
	0x82, 0x71, 0x41, 0x32, 0xc5, 0x50, 0x19, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0xc9,
	0x9e, 0x8b, 0x13, 0x62, 0x44, 0x41, 0x4e, 0x25, 0x39, 0x06, 0x18, 0x59, 0x71, 0xb1, 0x80, 0x0c,
	0x10, 0x32, 0xe2, 0xe2, 0x82, 0x18, 0x04, 0x56, 0x2f, 0xa8, 0x07, 0x72, 0xa0, 0x1e, 0x92, 0xeb,
	0xa4, 0xf8, 0x91, 0x85, 0x0a, 0x72, 0x2a, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x9e, 0x31, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x42, 0xdf, 0xf7, 0xa5, 0xdd, 0x00, 0x00, 0x00,
}
